about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views
app_name = 'posts'
urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('', views.index, name='posts_index'),
    path('new/', views.new_post, name='new_post'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'),
    path('<str:username>/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
from posts import views

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path('404/', views.page_not_found),
    path('500/', views.server_error),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('текст поста',
                            help_text='Напишите, о чем ваш пост')
    pub_date = models.DateTimeField('Дата публикации',
                                    auto_now_add=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey(Group,
                              on_delete=models.SET_NULL,
                              blank=True,
                              null=True,
                              verbose_name='группа',
                              related_name='group_posts',
                              help_text='Выберите группу из списка')
    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField('текст комментария',
                            help_text='Напишите свой комментарий',
                            )
    created = models.DateTimeField('дата комментария',
                                   auto_now_add=True)

posts/forms.py
from .models import Post, Comment
from django import forms
from django.forms import Textarea


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['group', 'text', 'image']
        widgets = {
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст'
            }),
        }
        labels = {
            'group': ('Группа'),
            'text': ('Текст'),
            'image': ('Изображение'),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст'
            }),
        }

# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ["text"]
#         widgets = {"text": forms.Textarea(attrs={"cols": 80, "row": 5}), }

posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Group
from .forms import PostForm, CommentForm

User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/index.html',
                  {'page': page,
                   'post_list': post_list})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.all().order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request,
                  'posts/group.html',
                  {'group': group, 'page': page, 'posts': posts}
                  )


@login_required
def new_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:posts_index')
    form = PostForm()
    return render(request, 'posts/new_post.html', {'form': form})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    author_posts = author.posts.all().order_by('-pub_date')
    posts_count = author_posts.count()
    paginator = Paginator(author_posts, 5)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'author': author,
        'page': page,
        'posts_count': posts_count,
    }
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(author.posts, id=post_id)
    comments = post.comments.all()
    image = post.image
    posts_count = Post.objects.filter(author=author).count()
    form = CommentForm()
    context = {
        'form': form,
        'image': image,
        'comments': comments,
        'author': author,
        'post': post,
        'posts_count': posts_count,
        'post_id': post_id,
    }
    return render(request, 'post.html', context)


@login_required
def post_edit(request, username, post_id):
    profile = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, pk=post_id, author=profile)
    if request.user != profile:
        return redirect('posts:post', username=username, post_id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post',
                            username=request.user.username,
                            post_id=post_id)

    return render(
        request, 'new_post.html', {'form': form, 'post': post},
    )


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)


def add_comment(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post', username, post_id)

posts/templates/posts/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'posts:add_comment' post.author.username post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

posts/templates/posts/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{% endblock %}
{% block content %}
{% load user_filters %}
    <div class="container">
           <h1>{{ group.title }}</h1>
           <p>{{ group.description }}</p>
            <!-- Вывод ленты записей -->
                {% for post in page %}
                  <!-- Вот он, новый include! -->
                    {% include "post_item.html" with post=post %}
                {% endfor %}
    </div>

        <!-- Вывод паджинатора -->
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}

{% endblock %}

posts/templates/posts/index.html
{% extends "base.html" %} 
{% block title %} Последние обновления {% endblock %}

{% block content %}
<!-- Кеширование блока с записями -->
{% load cache %}
{% cache 20 index_page %}
    <div class="container">
           <h1> Последние обновления на сайте</h1>
            <!-- Вывод ленты записей -->
                {% for post in page %}
                  <!-- Вот он, новый include! -->
                    {% include "post_item.html" with post=post %}
                {% endfor %}
    </div>

        <!-- Вывод паджинатора -->
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}
{% endcache %}
{% endblock %}

posts/templates/posts/new_post.html
{% extends "base.html" %}

{% block title %}
{% if not post %} Добавить запись {% else %} Редактировать запись {% endif %}
{% endblock %}

{% block content %}
{% load user_filters %}

{% for error in form.errors %}
<div class="alert alert-danger" role="alert">
    {{ error|escape }}
</div>
{% endfor %}


    <h1>{% if not post %} Добавить запись {% else %} Редактировать запись {% endif %}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                    <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                    <div class="col-md-6">

                        {{ field|addclass:"form-control" }}

                        {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                        {% endif %}
                    </div>                
            </div>
        {% endfor %}

        <div class="col-md-6 offset-md-4">              
                <button type="submit" class="btn btn-primary">
                    {% if post %} Сохранить {% else %} Добавить {% endif %}
                </button>
                <span>{{ error }}</span>
        </div>
    </form>

{% endblock %}

posts/templates/posts/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

posts/templates/posts/post.html
{% extends "base.html" %}
{% block content %}
{% load user_filters %}

<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                <div class="card">
                        <div class="card-body">
                                <div class="h2">
                                    <!-- Имя автора -->
                                    {{ author.get_full_name }}
                                </div>
                                <div class="h3 text-muted">
                                     <!-- username автора -->
                                     @{{ author }}
                                </div>
                        </div>
                        <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                        Подписчиков: XXX <br />
                                        Подписан: XXX
                                        </div>
                                </li>
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                            <!--Количество записей -->
                                            Записей: {{ posts_count }}
                                        </div>
                                </li>
                        </ul>
                </div>
        </div>

        <div class="col-md-9">

            <!-- Пост -->  
            
                <div class="card mb-3 mt-1 shadow-sm">
                        {% load thumbnail %}
                            {% thumbnail image "960x339" crop="center" upscale=True as im %}
                                 <img class="card-img" src="{{ im.url }}">
                            {% endthumbnail %}
                        <div class="card-body">
                                <p class="card-text">
                                        <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                        <a href="/{{ author }}/"><strong class="d-block text-gray-dark">@{{ author }}</strong></a>
                                        <!-- Текст поста -->
                                        {{ post.text }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group ">
                                                <!-- если юзер равен автор -->
                                                {% if user == post.author %}
                                                <a class="btn btn-sm text-muted" href="/{{ author }}/{{ post_id }}/edit" role="button">Редактировать</a>
                                                {% endif %}
                                        </div>
                                        <!-- Дата публикации  -->
                                        <small class="text-muted">{{ post.pub_date|date:"d M Y" }}</small>
                                </div>
                        </div>
                </div>
     </div>
    </div>
</main>
{% include "posts/comments.html" %}
{% endblock %}

posts/templates/posts/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

    <!-- Отображение картинки -->
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}" />
    {% endthumbnail %}
    <!-- Отображение текста поста -->
    <div class="card-body">
      <p class="card-text">
        <!-- Ссылка на автора через @ -->
        <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
          <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
        </a>
        {{ post.text|linebreaksbr }}
      </p>
  
      <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
      {% if post.group %}
      <a class="card-link muted" href="{% url 'posts:group_posts' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
      {% endif %}
  
      <!-- Отображение ссылки на комментарии -->
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          {% if post.comments.exists %}
          <div>
            Комментариев: {{ post.comments.count }}
          </div>
          {% endif %}
          <a class="btn btn-sm btn-primary" href="{% url 'posts:post' post.author.username post.id %}" role="button">
            Добавить комментарий
          </a>
  
          <!-- Ссылка на редактирование поста для автора -->
          {% if user == post.author %}
          <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' post.author.username post.id %}" role="button">
            Редактировать
          </a>
          {% endif %}
        </div>
  
        <!-- Дата публикации поста -->
        <small class="text-muted">{{ post.pub_date }}</small>
      </div>
    </div>
  </div>

posts/templates/posts/profile.html
{% extends "base.html" %}
{% block content %}
{% load user_filters %}
{% load thumbnail %}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                    <div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        <!-- Имя автора -->
                                        {{ author.get_full_name }}
                                    </div>
                                    <div class="h3 text-muted">
                                         <!-- username автора -->
                                         @{{ author }}
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков: XXX <br />
                                            Подписан: XXX
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                                <!-- Количество записей -->
                                                Записей: {{ posts_count }}
                                            </div>
                                    </li>
                            </ul>
                    </div>
            </div>

            <div class="container">
                <h1> Последние обновления на сайте</h1>
                 <!-- Вывод ленты записей -->
                     {% for post in page %}
                       <!-- Вот он, новый include! -->
                         {% include "post_item.html" with post=post %}
                     {% endfor %}
            </div>  

                <!-- Здесь постраничная навигация паджинатора -->
                {% include "paginator.html" %}
     </div>
    </div>
</main>

{% endblock %}